### ISSUE TITLE
Setup Model Associations

### ISSUE THREAD

**Issue by samdakota** [blindsweatyhansolo/pitchr#10]
- USER has many PROJECTS
- PROJECT belongs to USER
- USER belongs to many PROJECTS
- PROJECTS belongs to many USERS
- USER has many SKILLS
- SKILL belongs to USER
- VOTE belongs to USER
- VOTE belongs to PROJECT
- PROJECT has many VOTES
- COMMENT belongs to USER
- COMMENT belongs to PROJECT
- USER has many COMMENTS
- PROJECT has many COMMENTS

**Comment by blindsweatyhansolo** [comment]
Model associations created. Dropped SKILL, dropping Keyword and ProjectKeyword for now, set as long term goal
