### ISSUE TITLE
Use bcrypt to hash passwords

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/pitchr#13]
### Hash USER passwords with bcrypt
- Use **hooks** to has passwords collected from new User POST route
- Update USER model with **hooks**
  - define **beforeCreate()** with **bcrypt.hash()**
  - define **beforeUpdate()** with **bcrypt.hash()**
 
![Capture](https://user-images.githubusercontent.com/96745883/170157445-00e64a13-5e9e-4fb9-86fe-06e573f43055.PNG)

![Capture2](https://user-images.githubusercontent.com/96745883/170157614-eed1ea98-b3fc-4c18-a992-21e2620f2ba5.PNG)

**Comment by hlee92** [comment]
setup hashing with bcrypt sync
