### ISSUE TITLE
Create LOGIN route in USER routes

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/pitchr#14]
### Create LOGIN functionality
_Using a POST request route within /api/user-routes.js, create a route for login requests. Using a POST method is a more secure way of transferring data from client to server_

- Create an _INSTANCE METHOD_  called **checkPassword()** in the **User** model for checking passwords, using **bcrypt's compareSync()** method
- POST route will be found at _/login_
- Use **findOne** to find a User by their email
- Verify User password using **checkPassword()** created in User model

**Comment by hlee92** [comment]
created login route within user routes with instance method
