### ISSUE TITLE
Create Single-Project page template with data

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/pitchr#19]
_When a user clicks on an existing Project card, they are redirected to this Single-Project page using the GET route from homeRoutes_

- Include:
  - Project card (using project partial)
  - Project comments (using comment partial)
  - Comment form
    - On submit: performs POST request for new comment then reloads Single-Project page to display updated comments

**Comment by samdakota** [comment]
Removed "- Disable or hide comment form for non-logged in users (session)" since entire project view will be disabled without loggedIn
