### ISSUE TITLE
Establish backend session

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/pitchr#20]
_Using express-session and connect-session-sequelize, create a session on the back-end so that certain functionality is only available to logged in users_

### Update server.js with session variables
- requires **session**
- requires **SequelizeStore**
- define **sess**
  - Set maxlife for **cookie**
  - Use environment variable to hide **secret**

### Update routes with using session
- In homeRoute for 'login' page, update logic to check for session, and redirect to homepage if true, otherwise render login page and pass in loggedIn variable
- Update routes to use **req.session.save()** when: 
  - creating a new User (POST)
  - logging in (User - POST)
- Update routes to pass session variables to page templates for use in hiding/disabling functionality for non-logged in users:
  - Homepage
  - Single-Project
  - Dashboard/Favorites
  - Edit Project
  - Edit Comment

**Comment by hlee92** [comment]
Imported all expression session variables to server. Updated user routes with session variables and created logout route with session destroy.

**Comment by blindsweatyhansolo** [comment]
Used session variables to update voting routes

**Comment by blindsweatyhansolo** [comment]
Used a 'splash' message to display to new/nonlogged in users who visit the root page, with a link to login before being able to access the site.
