### ISSUE TITLE
Create Helpers

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/pitchr#27]
_Maybe we can find an NPM package to reach these functionality points?_

### Word Pluralization:
- Create function to pluralize ‘comment’ when there are more than 1 comments to a Project

### Date Formats:
- Create function to change from standard date display to a more clean format (MM/DD/YYYY)

### Authentication:

- Create an AuthGuard route [withAuth] using session to redirect non-logged in users to the LOGIN page when trying to access certain features such as:
  - Posting new Project
  - Commenting on an existing Project
  - Voting on an existing Project

### Project Value:

-Create function to translate project.value to 'open' or 'closed'

**Comment by samdakota** [comment]
**Word Pluralization**, **Date Formats**, and **Project Value** all created in 'utils/helper.js' as:

-formatPlural()
-formatDate()
-projectOpen()

Jest installed, added to package.json script, and completed tests for all three helper functions.

**Comment by samdakota** [comment]
Authentication created in 'utils/auth.js' as: 

-withAuth()
