### ISSUE TITLE
Establish CRUD routes for USER model

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/pitchr#4]
## USER Model Routes
_CRUD routes for USER model will be found in /controllers/api/user-routes.js_

- GET all users
- GET single user (via PrimaryKey/id)
- POST create new user
- PUT update user password (via PrimaryKey/id)
- DELETE remove user (via PrimaryKey/id)

## Set up /api/index.js
_Once USER model routes have been established, set up /controllers/api/index.js_
- Use **express Router**
- define userRoutes to require user-routes.js
- Use router.us() to define the appendage '/users' to all userRoutes
- Export!

**Comment by hlee92** [comment]
I will send what I have through slack, but I'm going to close out this issue
