### ISSUE TITLE
Create an Edit-Profile Page template with data

### ISSUE THREAD

**Issue by samdakota** [blindsweatyhansolo/pitchr#46]
_When a user clicks on EDIT button on their Profile from the Profile page:_

Redirect to Edit-Profile page

Edit Profile Form:

- Allow user to edit email
- Allow user to edit github
- Allow user to edit description
- Allow user to delete Profile (DELETE request from Profile routes and DESTROY session)
- On submitting edits, gather form data and perform PUT request for Profile, redirect to Profile page for updated Profile to display updated information

**Comment by blindsweatyhansolo** [comment]
Created Edit-Profile page with two sections: updating user information and deleting user data
Updating user information gathers new values or uses default input values (set as user data) then performs a PUT request to update user info, redirects to Profile page on success
Delete section contains a button with a warning that performs a DELETE request to delete a user from the database, kills current session and redirects to the homepage
