### ISSUE TITLE
Create VOTE Model

### ISSUE THREAD

**Issue by samdakota** [blindsweatyhansolo/pitchr#8]
ID 
- INTEGER 
- Cannot be NULL
- Primary Key
- Auto-Increment

USER
- Cannot be NULL
- References USER Model’s primary key

PROJECT
- Cannot be NULL
- References PROJECT Model’s primary key

**Comment by blindsweatyhansolo** [comment]
VOTE model created, keeping this issue open because can't test model method for gathering vote totals until merged with all models and associations established. Commented out all required code blocks, probably needs to be tweaked

**Comment by blindsweatyhansolo** [comment]
Updated and testing with necessary merge. Vote model now works as a _through_ model for associating **Users** and **Projects** through the **Vote** table so votes can be limited to _one vote per user per project, but many votes across project from multiple users_
